### ISSUE TITLE
Modules Not Detected

### ISSUE THREAD

**Issue by losso17** [MobiFlight/MobiFlight-Connector#454]
Where could i go wrong....

After Installation, i'm unable to get the connector running.. seems that the module is not installed..

event Modules folder copied to community...

![Desktop Screenshot 2021 08 25 - 19 18 16 22_LI](https://user-images.githubusercontent.com/89477038/130782652-145e19dc-5290-4c41-a2f8-0073a4693a8a.jpg)

 - MobiFlight Version: [9.0.0]
 - FlightSim: [MSFS2020]
 - AddOn: [a32nx, fsuipc7, flight tracker plugin]

**Comment by Mobiflight** [comment]
`offline mode is active, is that on purpose?

**Comment by losso17** [comment]
How to get it online?

**Comment by Mobiflight** [comment]
disable offline mode in Settings

**Comment by losso17** [comment]
done....where can i get the modules running ...eg mobiflight mega

**Comment by losso17** [comment]
![Desktop Screenshot 2021 08 30 - 18 31 25 62_LI](https://user-images.githubusercontent.com/89477038/131326541-96a079ad-4756-47a4-ae8d-efd0115a125e.jpg)

**Comment by MobiFlight-Admin** [comment]
@losso17 - I am sorry, I am travelling. Have you been able to resolve the problem? Maybe you are still missing the specific drivers for your Arduino board. There are installation instructions for different boards here: https://www.mobiflight.com/en/documentation/module.html#installation

**Comment by losso17** [comment]
Thanks for your reply... is there anyway i can get some of my msfs sim button running using streamdeck via mobiflight.... without any board?

**Comment by MobiFlight-Admin** [comment]
Can you explain more what you are trying to do?

**Comment by MobiFlight-Admin** [comment]
@losso17 - I need more information on this issue. 

Suggestion: Have you been able to install the drivers for your arduino and try again?

I don't know how the first bug report and the streamdeck question go together. Please help to clarify.

**Comment by DocMoebiuz** [comment]
Please try with the latest firmware. I will close this. feel free to re-open if requried.
