### ISSUE TITLE
Mobiflight 9.0.0.6 exception related to joystick code

### ISSUE THREAD

**Issue by jc13git** [MobiFlight/MobiFlight-Connector#529]
**Describe the bug**
On initial startup Mobiflight crashes when scanning joysticks if my homemade Teensyduino stick is attached.  This is based off the code from here:   https://forum.pjrc.com/threads/23681-Many-axis-joystick. 

In windows, the stick shows up as X, Y, Z, Xrot, Yrot, Zrot, two sliders, and 32 buttons (as in attached screenshot).

************** Exception Text **************
System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at MobiFlight.Joystick.IsValidAxis(Int32 i)
   at MobiFlight.Joystick.UpdateAxis(JoystickState newState)
   at MobiFlight.Joystick.Update()
   at MobiFlight.JoystickManager.PollTimer_Tick(Object sender, EventArgs e)
   at System.Windows.Forms.Timer.OnTick(EventArgs e)
   at System.Windows.Forms.Timer.TimerNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

**Steps To Reproduce**
1. Start Mobiflight with the stick attached
2. Click on Run
3. Exception appears

Works fine with stick unplugged, or plugging stick after Mobiflight is initially started.  Briefly discussed in the discord at https://discord.com/channels/608690978081210392/745361245808492584/902676388224593932

**Details**
 - MobiFlight Version: 9.0.0.6
 - FlightSim: FS2020
 - AddOn: [e.g. Default Aircraft
[mobiexception.txt](https://github.com/MobiFlight/MobiFlight-Connector/files/7421977/mobiexception.txt)
![windowsjoy](https://user-images.githubusercontent.com/43517966/138973796-8f22f9b4-67fb-480d-9513-dc6708299ebf.png)

**Comment by MobiFlight-Admin** [comment]
@jc13git - Please confirm that this is fixed with 9.0.0.7

**Comment by jc13git** [comment]
This is still an issue in 9.0.0.7.  I believe I first noticed it in .6 but reverting to .4 had no problem.  I guess that's when the joystick code made its way in.

**Comment by MobiFlight-Admin** [comment]
@jc13git This should be fixed in 9.1 - please confirm

**Comment by jc13git** [comment]
All good now - thanks!
